import { PCCConvenienceFunctions } from "@pantheon-systems/pcc-react-sdk";
import { NextSeo } from "next-seo";
import Image from "next/image";
import { ArticleGrid } from "../components/grid";
import Layout from "../components/layout";

export default function Search({ articles, searchString, summary }) {
  const HomepageHeader = () => (
    <div className="prose sm:prose-xl mx-auto mt-20 flex max-w-fit flex-col">
      <h1 className="prose h-full text-center text-4xl">
        Welcome to{" "}
        <a
          className="text-blue-600 no-underline hover:underline"
          href="https://nextjs.org"
        >
          Next.js!
        </a>
      </h1>
      <div className="text-2xl">
        <div className="flex items-center justify-center rounded bg-black p-4 text-white">
          Decoupled PCC on{" "}
          <Image
            src="/pantheon.png"
            alt="Pantheon Logo"
            style={{
              margin: 0,
            }}
            width={191}
            height={60}
          />
        </div>
      </div>
    </div>
  );

  return (
    <Layout>
      <NextSeo
        title="Decoupled Next PCC Demo"
        description="Generated by create-pantheon-decoupled-kit."
      />
      <HomepageHeader />
      <section className="mx-auto my-4 max-w-[720px] rounded-lg border-2 bg-green-400/10">
        <div className="mt-4 text-center text-sm">
          ✨ Generative AI is experimental
        </div>
        <div className="px-4 py-4">
          {summary ? (
            summary
          ) : (
            <i>No generative AI results available for this search</i>
          )}
        </div>
      </section>
      <h3 className="mt-4 text-center text-3xl">
        Search results for &quot;{searchString}&quot;
      </h3>
      <section>
        <ArticleGrid articles={articles} />
      </section>
    </Layout>
  );
}

export async function getServerSideProps({ query }) {
  const { articles, summary } =
    await PCCConvenienceFunctions.getAllArticlesWithSummary(
      {
        publishingLevel: "PRODUCTION",
      },
      {
        titleContains: query.q,
        tagContains: query.q,
        bodyContains: query.q,
      },
      true,
    );

  return {
    props: {
      articles,
      summary,
      searchString: query.q,
    },
  };
}
