import { PCCConvenienceFunctions } from "@pantheon-systems/pcc-react-sdk/server";
import ArticleList from "../../components/article-list";
import Layout from "../../components/layout";
import { PAGE_SIZE } from "../../constants";

export default async function ArticlesListTemplate() {
  const {
    data: articles,
    cursor,
    totalCount,
  } = await PCCConvenienceFunctions.getPaginatedArticles({
    pageSize: PAGE_SIZE,
  });

  return (
    <Layout>
      <section className="max-w-screen-3xl mx-auto px-4 pt-16 sm:w-4/5 md:w-3/4 lg:w-4/5 2xl:w-3/4">
        <ArticleList
          articles={articles}
          cursor={cursor}
          totalCount={totalCount}
        />
      </section>
    </Layout>
  );
}

export function generateMetadata() {
  return {
    title: "Decoupled Next PCC Demo",
    description: "Generated by create-pantheon-decoupled-kit.",
  };
}
