import { PCCConvenienceFunctions } from "@pantheon-systems/pcc-react-sdk/server";
import ArticleList from "../../components/article-list";
import Layout from "../../components/layout";
import { PAGE_SIZE } from "../../constants";

async function fetchNextPages(cursor: string) {
  "use server";
  const { data, cursor: newCursor } =
    await PCCConvenienceFunctions.getPaginatedArticles({
      pageSize: PAGE_SIZE,
      cursor,
    });
  return {
    data,
    newCursor,
  };
}

export default async function ArticlesListTemplate() {
  const {
    data: articles,
    cursor,
    totalCount,
  } = await PCCConvenienceFunctions.getPaginatedArticles({
    pageSize: PAGE_SIZE,
  });

  return (
    <Layout>
      <ArticleList
        articles={articles}
        cursor={cursor}
        totalCount={totalCount}
        fetcher={fetchNextPages}
      />
    </Layout>
  );
}

export async function generateMetadata() {
  return {
    title: "Decoupled Next PCC Demo",
    description: "Generated by create-pantheon-decoupled-kit.",
  };
}
