import { NextSeo } from "next-seo";
import Link from "next/link";

import PageHeader from "../../components/page-header";
import Layout from "../../components/layout";

export default function ExamplesPageTemplate() {
  return (
    <Layout>
      <NextSeo
        title="Decoupled Next PCC - Examples"
        description="Generated by create-pantheon-decoupled-kit."
      />
      <PageHeader title="Examples" />
      <section className="prose lg:prose-xl mt-10 flex flex-col mx-auto max-h-screen">
        <div className="max-w-lg mx-auto lg:grid-cols-3 lg:max-w-screen-lg">
          <Link passHref href="/">
            <span className="w-full underline cursor-pointer">Home &rarr;</span>
          </Link>
          <p>
            This page outlines a growing list of common use cases that can be
            used as a reference when building using this starter kit. If you
            don&apos;t need them for your site, feel free to delete the
            `pages/examples` directory in your codebase.
          </p>
          <ul>
            <li>
              <Link href="/examples/ssg-isr">SSG and ISR</Link> - by default,
              this starter kit is optimized for SSR and Edge Caching on
              Pantheon. This example is provided for cases where Next.js static
              generation options would be beneficial.
            </li>
            <li className="opacity-30">
              <Link href="#">API Authorization</Link> - confirms that Next.js is
              able to make authenticated requests to Pantheon Content
              Cloud&apos;s API.
            </li>
            <li className="opacity-30">
              <Link href="#">Pagination</Link> - a paginated list with a large
              dataset.
            </li>
          </ul>
        </div>
      </section>
    </Layout>
  );
}
