import React from "react";
import Layout from "../components/layout";
import { PostGrid } from "../components/grid";

export default function Home({ ...props }) {
  const { articles } = props.pageContext;

  const HomepageHeader = () => (
    <div className="flex flex-col mx-auto mt-20 prose sm:prose-xl max-w-fit">
      <h1 className="h-full text-4xl prose text-center">
        Welcome to{" "}
        <a
          className="text-blue-600 no-underline hover:underline"
          href="https://gatsbyjs.com"
        >
          Gatsby
        </a>
      </h1>
      <div className="mt-8 text-2xl">
        <div className="flex items-center justify-center p-4 text-white bg-black rounded">
          Decoupled PCC on{" "}
          <img
            src="/pantheon.png"
            alt="Pantheon Logo"
            style={{
              margin: 0,
            }}
            width={191}
            height={60}
          />
        </div>
      </div>
    </div>
  );

  return (
    <Layout
      pageTitle="Decoupled Gatsby PCC Demo"
      pageDescription="Generated by create-pantheon-decoupled-kit."
    >
      <HomepageHeader />
      <section>
        <PostGrid contentType="posts" data={articles} />
      </section>
    </Layout>
  );
}
