import { PCCConvenienceFunctions } from "@pantheon-systems/pcc-sdk-core";
import Image from "next/image";
import { PostGrid } from "../components/grid";
import Layout from "../components/layout";

export default async function Home() {
  const articles = await PCCConvenienceFunctions.getAllArticles({
    publishingLevel: "PRODUCTION",
  });

  const HomepageHeader = () => (
    <div className="flex flex-col mx-auto mt-20 prose sm:prose-xl max-w-fit">
      <h1 className="h-full text-4xl prose text-center">
        Welcome to{" "}
        <a
          className="text-blue-600 no-underline hover:underline"
          href="https://nextjs.org"
        >
          Next.js!
        </a>
      </h1>
      <div className="text-2xl">
        <div className="flex items-center justify-center p-4 text-white bg-black rounded">
          Decoupled PCC on{" "}
          <Image
            src="/pantheon.png"
            alt="Pantheon Logo"
            style={{
              margin: 0,
            }}
            width={191}
            height={60}
          />
        </div>
      </div>
    </div>
  );

  return (
    <Layout>
      <HomepageHeader />
      <section>
        <PostGrid contentType="posts" data={articles} />
      </section>
    </Layout>
  );
}

export async function generateMetadata({}) {
  return {
    title: "Decoupled Next PCC Demo",
    description: "Generated by create-pantheon-decoupled-kit.",
  };
}
