import { PCCConvenienceFunctions } from "@pantheon-systems/pcc-react-sdk/server";
import Image from "next/image";
import Layout from "../../components/layout";
import { Tags } from "../../components/tags";
import TagResults from "./tag-results";

export default async function TagSearch({ searchParams }) {
  const [articles, tags] = await Promise.all([
    await PCCConvenienceFunctions.getAllArticles(
      {
        publishingLevel: "PRODUCTION",
      },
      {
        tagContains: searchParams.q,
      },
    ),
    PCCConvenienceFunctions.getTags(),
  ]);

  const searchString = searchParams.q || "";

  const HomepageHeader = () => (
    <div className="prose sm:prose-xl mx-auto mt-20 flex max-w-fit flex-col">
      <h1 className="prose h-full text-center text-4xl">
        Welcome to&quot;
        <a
          className="text-blue-600 no-underline hover:underline"
          href="https://nextjs.org"
        >
          Next.js!
        </a>
      </h1>
      <div className="text-2xl">
        <div className="flex items-center justify-center rounded bg-black p-4 text-white">
          Decoupled PCC on{" "}
          <Image
            src="/pantheon.png"
            alt="Pantheon Logo"
            style={{
              margin: 0,
            }}
            width={191}
            height={60}
          />
        </div>
      </div>
    </div>
  );

  return (
    <Layout>
      <HomepageHeader />
      <TagResults articles={articles} searchString={searchString} />
      <div className="mx-auto mt-16 max-w-screen-lg">
        <h3>Site-wide</h3>
        <Tags tags={tags} />
      </div>
    </Layout>
  );
}

export function generateMetadata() {
  return {
    title: "Decoupled Next PCC Demo",
    description: "Generated by create-pantheon-decoupled-kit.",
  };
}
